trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main
  paths:
    include:
    - package.json
    - package-lock.json
    - eng/pipelines/typespec-ci.yml
    - eng/pipelines/templates/steps/typespec-ci.yml

jobs:
- job: TypeSpecCI
  pool:
    name: azsdk-pool-mms-ubuntu-2204-general
    vmImage: ubuntu-22.04
  variables:
    - name: TypeSpecFolders
      value: >
        "@{
        Contoso.WidgetManager='specification/contosowidgetmanager/Contoso.WidgetManager';
        AnomalyDetector='specification/cognitiveservices/AnomalyDetector';
        ContentSafety='specification/cognitiveservices/ContentSafety';
        healthinsights.openapi='specification/cognitiveservices/HealthInsights/healthinsights.openapi';
        OpenAI.Inference='specification/cognitiveservices/OpenAI.Inference';
        Fleet.Management='specification/containerservice/Fleet.Management';
        Microsoft.ServiceNetworking='specification/servicenetworking/ServiceNetworking.Management';
        AI.TextTranslation='specification/translation/Azure.AI.TextTranslation';
        }"

  steps:
  - script: npm ci
    displayName: npm ci

  - script: npm ls -a
    displayName: npm ls -a

  - template: templates/steps/typespec-ci.yml
    parameters:
      Folders: ${{TypeSpecFolders}}
