trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main
  paths:
    include:
    - package.json
    - package-lock.json
    - eng/pipelines/typespec-ci.yml
    - eng/pipelines/templates/steps/typespec-ci.yml

jobs:
- job: TypeSpecCI
  pool:
    name: azsdk-pool-mms-ubuntu-2204-general
    vmImage: ubuntu-22.04
  variables:
    - name: TypeSpecFolders
      value: >
        "specification/contosowidgetmanager/Contoso.WidgetManager,
        specification/cognitiveservices/AnomalyDetector,
        specification/cognitiveservices/ContentSafety,
        specification/cognitiveservices/HealthInsights/healthinsights.openapi,
        specification/cognitiveservices/OpenAI.Inference,
        specification/containerservice/Fleet.Management,
        specification/servicenetworking/ServiceNetworking.Management,
        specification/translation/Azure.AI.TextTranslation"

  steps:
  - script: npm ci
    displayName: npm ci

  - script: npm ls -a
    displayName: npm ls -a

  - ${{ each folder in split(variables.TypeSpecFolders, ',') }}:
    - template: templates/steps/typespec-ci.yml
      parameters:
        Folder: ${{ folder }}
        displayName: ${{ split('$(folder)', '/')[-1] }}